"""
This file is just the boot method to load some stuff
Do not edit this file, it could break pullit
"""
from ruamel import yaml
from modules.core.notifications import Notifications
from modules.core.database import Database


class Boot:

    # Boot constructor
    def __init__(self):
        self.database = Database().get()
        self.config = yaml.safe_load(open('./config.yml'))
        self.notifications = Notifications()


boot = Boot()
